### ISSUE TITLE
Unable to call Stripe.setPublishableKey on Client Start or Template Rendered

### ISSUE THREAD

**Issue by patrickml** [benjick/meteor-stripe-native#3]
When I try to run `Stripe.setPublishableKey(Meteor.settings.public.STRIPE_PUBLISHABLE);` on either a `Meteor.startup()` or a `Template.name.onRendered()` I receive the error `Cannot read property 'setPublishableKey' of undefined` however if I run the function in the console it works. I believe this is because Stripe has not yet been initialized on the client.

**Comment by patrickml** [comment]
Turns out its from adding `benjick:meteor-stripe-native` as a depend to another package and exporting `Stripe` I wonder if `Stripe` should be renamed within this package to ensure there is no conflict

**Comment by benjick** [comment]
I think you have to define Stripe and export it yourself if you use api.use instead of api.imply. How are you depending on this package?

**Comment by benjick** [comment]
Are you doing `weak: true`?

From the docs

> When you weakly depend on a package you don't see its exports.

**Comment by benjick** [comment]
I'm closing this, feel free to open if you have the same error
